### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by jure** [pagekit/vagrant#5]
I was unable to get Pagekit installed in a VM using this repository, so I'm wondering if the project is defunct.

**Comment by saschadube** [comment]
We are working on a [new version!](https://github.com/pagekit/pagekit/commits/develop). We will have news very soon

**Comment by jure** [comment]
Great! Might make sense to put a notice in the README about the status of this repository, so that people don't spend time trying to set up the new PageKit using this approach (like I did)

**Comment by Jinksi** [comment]
Please let us know in the readme. I was left scratching my head after the install.
